Investigate necessary log level changes REMReM and Translator
eiffel-community/eiffel-remrem-publish pull request #275
Opened 2023-08-16 10:18 UTC by vishnu-alapati

…info

### Applicable Issues

### Description of the Change

While the log level is INFO, we are not seeing eventID and HttpStatus code in catalina files. So, Made the necessary changes to print them.

### Alternate Designs

### Benefits

### Possible Drawbacks

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Vishnu Alapati vishnu.alapati@tcs.com

2023-08-17 14:42 UTC, z-sztrom requested changes

2023-08-17 14:42 UTC, z-sztrom commented on publish-common/src/main/java/com/ericsson/eiffel/remrem/publish/helper/RMQHelper.java
> +        JsonParser parser = new JsonParser();
Instantiation of JsonParser is deprecated.

2023-08-17 14:42 UTC, z-sztrom commented on publish-common/src/main/java/com/ericsson/eiffel/remrem/publish/helper/RabbitMqProperties.java
> +    public void send(String routingKey, String msg, String EventId)
EventId should  be eventId.

2023-08-22 06:32 UTC, vishnu-alapati commented on publish-service/src/main/java/com/ericsson/eiffel/remrem/publish/controller/ProducerController.java
> +            log.info("HTTP Status: {}",  messageService.getHttpStatus().value());
We are already printing the eventId before this message like this Published message 1ec3101e-4c6f-4364-a0d5-63f91d1b3050 with size 813 bytes on exchange 'test' with routing key '#'

2023-08-24 06:52 UTC, piyush-sadangi approved these changes
Looks good to me

2023-08-25 08:54 UTC, z-sztrom requested changes
Just a typo in the code. Otherwise it looks fine and tests passed.

2023-08-25 08:54 UTC, z-sztrom commented on publish-common/src/main/java/com/ericsson/eiffel/remrem/publish/helper/RMQHelper.java
> +        String evnetId = msgService.getEventId(getGson().fromJson(msg, JsonObject.class));
evnetId -> eventId

2023-08-25 08:54 UTC, z-sztrom commented on publish-service/src/main/java/com/ericsson/eiffel/remrem/publish/controller/ProducerController.java
> +            log.info("HTTP Status: {}",  messageService.getHttpStatus().value());
Yes, OK. But we should improve that in a future. Otherwise parsing may be tricky when parallel publishing is enabled...

2023-08-25 09:55 UTC, vishnu-alapati commented on publish-common/src/main/java/com/ericsson/eiffel/remrem/publish/helper/RMQHelper.java
> +        String evnetId = msgService.getEventId(getGson().fromJson(msg, JsonObject.class));
modified the name

2023-08-25 13:53 UTC, z-sztrom approved these changes
Works fine.

2023-08-28 06:18 UTC, merged